t3n:
  GraphQL:
    endpoints:
      'media-assets':
        logRequests: false
        context: 'Flowpack\Media\Ui\GraphQL\Context\AssetSourceContext'
        errorTransform: 'Flowpack\Media\Ui\GraphQL\Transform\FlowErrorTransform'
        schemas:
          root:
            typeDefs: 'resource://Flowpack.Media.Ui/Private/GraphQL/schema.root.graphql'
            resolverPathPattern: 'Flowpack\Media\Ui\GraphQL\Resolver\Type\{Type}Resolver'
            resolvers:
              AssetProxy: 'Flowpack\Media\Ui\GraphQL\Resolver\Type\AssetResolver'
